version: 2
updates:
  - package-ecosystem: "docker"
    directory: "federal/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5
    labels:
      - "docker"